### ISSUE TITLE
Groundtruth point-to-point map

### ISSUE THREAD

**Issue by zss1995** [LIX-shape-analysis/GeomFmaps#4]
Hello, I'm sorry to bother you again. I'm trying to evaluate the matching results, and there's some question about the  groundtruth point-to-point map, for the number of points between shapes is different in each dataset(some shapes have slightly more points, some have fewer), and I don't know how to generate the groundtruth data.

**Comment by nicolasdonati** [comment]
Hi ! Your concern is perfectly legit, since I hadn't made ground-truths available. Now they should be, on the same link as the one you used for the datasets. There are two types of ground-truths here (yes, it's never easy ...).
-- For FAUST_r and SCAPE_r, they are under .vts files. Each .vts stores one array with exactly 5k entries, which is a map from a template (with 5k points) to the re-meshed shape (which has around 5k points, but it can vary). Be aware that this map is not bijective in general. Then to evaluate on these datasets, you use these .vts maps to mimic a ground-truth. It should be in the eval codes provided here. Also, you may notice that some .sym.vts are also provided. You should not need them, they store the map from the template to the intrinsic left-right symmetry of the re-meshed shape.
-- For SHREC_r, normal ground-truths are provided. Here too, the eval codes provided should show you how to use them.

**Comment by zss1995** [comment]
Thank you for your reply!
