### ISSUE TITLE
Surface preprocess

### ISSUE THREAD

**Issue by michaelzhou0723** [LIX-shape-analysis/GeomFmaps#5]
Thanks for providing all the code! It's extremely helpful. I have a question about data preprocessing. Specifically, why is surface area normalization necessary? How would the performance drop if there's no such a step?

**Comment by nicolasdonati** [comment]
You're welcome !
It is necessary because in the provided version of the code, the data is not augmented with respect to the scale. Namely, all the training shapes have their original scale at train time. So, at test time, if the scale of your test shapes happens to be different than the scale of your train shapes, you'll probably end up getting bad results. To avoid this kind of problem, we simply recommend you put all your shapes [train&test] to the same scale (for instance, total area to 1, which is actually a common setting).
